version: '3'

services:
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis-xwiki-matrix
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - internal

  xmatrix-bot:
    container_name: xwiki-matrix-bot
    image: gridexx/xwiki-matrix-bot:latest
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env.production
    networks:
      - internal

volumes:
  redis_data:
    driver: local

networks:
  internal: